### ISSUE TITLE
PlotMe Worldedit Creative World

### ISSUE THREAD

**Issue by cdt35** [TranscendenceGN/TGN#10]
I think it would be cool if we set up a plotme world with worldedit enabled. The two plugins are compatible with eachother so nobody can grief with worledit.

**Comment by Starza4TW** [comment]
WorldEdit also works with WorldGuard which we will continue to use to protect regions in the creative world. In addition, very few people will receive WorldEdit permissions within the creative world. It is *possible* builders may get some perms, but not all. However, we are looking at getting plots for TGN for other uses in the future.
